### ISSUE TITLE
Tiến độ tiến hành chương Deep Learning Computation

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#1015]
Mình hy vọng chương **Deep Learning Computation** này (47 phần) chúng ta có thể hoàn thiện trước 05/05/2020.

## Giai đoạn 1 `29 parts`
* [x] 5.0 [Deep Learning Computation - Index](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+index_vn+label%3A%22chapter%3A+deep-learning-computation%22) `01 part`
* [x] 5.1. [Layers and Blocks](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+model-construction_vn+label%3A%22chapter%3A+deep-learning-computation%22+) `06 parts`
* [x] 5.2. [Parameter Management](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+parameters_vn+label%3A%22chapter%3A+deep-learning-computation%22+) `05 parts`
* [x] 5.3. [Deferred Initialization](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+deferred-init_vn+label%3A%22chapter%3A+deep-learning-computation%22+) `04 parts`
* [x] 5.4. [Custom Layers](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+custom-layer_vn+label%3A%22chapter%3A+deep-learning-computation%22+) `03 parts`
* [x] 5.5. [File I/O](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+read-write_vn+label%3A%22chapter%3A+deep-learning-computation%22+) `03 parts`
* [x] 5.6. [GPUs](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+use-gpu_vn+label%3A%22chapter%3A+deep-learning-computation%22+) `07 parts`

## Giai đoạn 2 `18 parts`
* [x] 5.0 [Deep Learning Computation - Index](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+index_vn+label%3A%22chapter%3A+deep-learning-computation%22+label%3A%22status%3A+phase+2%22+) `01 part`
* [x] 5.1. [Layers and Blocks](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+model-construction_vn+label%3A%22chapter%3A+deep-learning-computation%22+label%3A%22status%3A+phase+2%22+) `04 parts`
* [x] 5.2. [Parameter Management](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+parameters_vn+label%3A%22chapter%3A+deep-learning-computation%22+label%3A%22status%3A+phase+2%22+) `03 parts`
* [x] 5.3. [Deferred Initialization](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+deferred-init_vn+label%3A%22chapter%3A+deep-learning-computation%22+label%3A%22status%3A+phase+2%22+) `02 parts`
* [x] 5.4. [Custom Layers](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+custom-layer_vn+label%3A%22chapter%3A+deep-learning-computation%22+label%3A%22status%3A+phase+2%22+) `02 parts`
* [x] 5.5. [File I/O](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+read-write_vn+label%3A%22chapter%3A+deep-learning-computation%22+label%3A%22status%3A+phase+2%22+) `02 parts`
* [x] 5.6. [GPUs](https://github.com/aivivn/d2l-vn/issues?q=is%3Aissue+use-gpu_vn+label%3A%22chapter%3A+deep-learning-computation%22+label%3A%22status%3A+phase+2%22) `04 parts`

**Comment by tiepvupsu** [comment]
Nếu 15/4 xong chương 4 thì chương này khoảng 5/5 sẽ xong. Chương này khá ngắn.

**Comment by duythanhvn** [comment]
Em đang nghĩ và thấy hay là để xong chương 5, rơi vào tầm 30/4 mình công bố cả hai chương. Chương 5 này sắp xong giai đoạn 1 rồi anh này.

**Comment by tiepvupsu** [comment]
> Em đang nghĩ và thấy hay là để xong chương 5, rơi vào tầm 30/4 mình công bố cả hai chương. Chương 5 này sắp xong giai đoạn 1 rồi anh này.

Anh sử description của chương về 05/05. Tới khoảng 25/4 mình xem tiến độ thế nào. Nếu nhanh thì kéo về 30/4.

Giả sử chương 5 xong được trong tháng 4 thì mình còn 13 chương, cần làm trong 8 tháng để hoàn thiện trong năm 2020. Sẽ cần anh em ủng hộ dài dài.
