### ISSUE TITLE
Dịch hình "dropout_vn" - Phần 3

### ISSUE THREAD

**Issue by tamnguyenvan** [aivivn/d2l-vn#1034]
Hình ảnh cần dịch: `.../img/dropout2.svg`.
| Tiếng Anh | Tiếng Việt |
|:---|:---|
| MLP with one hidden layer | MLP với một tầng ẩn |
|Hidden layer after dropout | Tầng ẩn sau khi dùng dropout |

**Comment by duythanhvn** [comment]
@sudohainguyen Chiến không em?

**Comment by rootonchair** [comment]
Mình thấy ổn. Nếu @sudohainguyen đưa vào hình nhé

**Comment by sudohainguyen** [comment]
> @sudohainguyen Chiến không em?

chơi anh ơi

**Comment by duythanhvn** [comment]
Cậu trai kẻ cái bảng điền nội dung sai vãi

**Comment by tamnguyenvan** [comment]
@duythanhvn :))) đã update ạ.
