### ISSUE TITLE
Dịch ảnh chương 6 - Phần 1

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#1181]
Các hình cần dịch:
* [correlation.svg](https://github.com/aivivn/d2l-vn/blob/master/img/correlation.svg)
* [conv-pad.svg](https://github.com/aivivn/d2l-vn/blob/master/img/conv-pad.svg)
* [conv-stride.svg](https://github.com/aivivn/d2l-vn/blob/master/img/conv-stride.svg)
* [conv-multi-in.svg](https://github.com/aivivn/d2l-vn/blob/master/img/conv-multi-in.svg)
* [conv-1x1.svg](https://github.com/aivivn/d2l-vn/blob/master/img/conv-1x1.svg)

Xem hướng dẫn dịch hình ảnh tại [đây](https://github.com/aivivn/d2l-vn/blob/master/img/README.md)

**Comment by rootonchair** [comment]
Các ảnh chỉ bao gồm các từ được lặp lại nên bạn có thể gộp chung về một bảng

**Comment by rootonchair** [comment]
@sudohainguyen Bạn muốn nhận phần này chứ?

**Comment by sudohainguyen** [comment]
> @sudohainguyen Bạn muốn nhận phần này chứ?

Oke bạn !
