### ISSUE TITLE
Dịch ảnh chương 6 - Phần 2

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#1182]
Các ảnh cần dịch: 
* [pooling.svg](https://github.com/aivivn/d2l-vn/blob/master/img/pooling.svg)
* [lenet.svg](https://github.com/aivivn/d2l-vn/blob/master/img/lenet.svg)
* [lenet-vert.svg](https://github.com/aivivn/d2l-vn/blob/master/img/lenet-vert.svg)

Xem hướng dẫn dịch hình ảnh tại [đây](https://github.com/aivivn/d2l-vn/blob/master/img/README.md)

**Comment by duythanhvn** [comment]
@sudohainguyen Nốt không em?

**Comment by sudohainguyen** [comment]
chơi anh ơi

**Comment by rootonchair** [comment]
@sudohainguyen đừng quên phần này nhé
