### ISSUE TITLE
Chỉnh lại một số sai sót trong glossary

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#130]
Trong [glossary của Machine Learning Yearning](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md), có các từ sau bị update sai trong glossary của D2L.

| Tiếng Việt | Tiếng Anh |
| :--- | :--- |
| underfit | dưới khớp |
| transcribe | phiên thoại |

@lkhphuc anh check lại giùm em nhé

**Comment by lkhphuc** [comment]
éc. Cảm ơn @rootonchair .
Transcribe thì là mình sơ sót, không nhớ kĩ, đúng là động từ thì "phiên thoại" hay hơn "ghi thoại" thật.
Còn Underfit thì mình dịch theo anh @tiepvupsu nhắc trong một comment gần đây trong một PR, hiện tại mình tìm lại không được.
Anh @tiepvupsu vô comment giùm em lại từ underfit được không?

**Comment by rootonchair** [comment]
@lkhphuc đây là phần thảo luận của "underfit"
https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/issues/391

**Comment by lkhphuc** [comment]
Ok thank @rootonchair nhiều.
Để mình sửa lại.
