### ISSUE TITLE
Dịch hình Modern CNN - P1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#1348]
Những hình cần dịch:
1. [vgg.svg](https://github.com/aivivn/d2l-vn/blob/master/img/vgg.svg)
2. [nin.svg](https://github.com/aivivn/d2l-vn/blob/master/img/nin.svg)
3. [inception.svg](https://github.com/aivivn/d2l-vn/blob/master/img/inception.svg)
4. [alexnet.svg](https://github.com/aivivn/d2l-vn/blob/master/img/alexnet.svg)

cc: @rootonchair

**Comment by rootonchair** [comment]
Em thấy tấm `inception-full` không cần dịch đâu anh
