### ISSUE TITLE
Dịch hình Modern CNN - P2

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#1349]
Những hình cần dịch:
1. [functionclasses.svg](https://github.com/aivivn/d2l-vn/blob/master/img/functionclasses.svg)
2. [residual-block.svg](https://github.com/aivivn/d2l-vn/blob/master/img/residual-block.svg)
3. [resnet-block.svg](https://github.com/aivivn/d2l-vn/blob/master/img/resnet-block.svg)
4. [ResNetFull.svg](https://github.com/aivivn/d2l-vn/blob/master/img/ResNetFull.svg)

cc: @rootonchair

**Comment by rootonchair** [comment]
Trong `resnet-block.svg` từ `Batch Norm` mình có nên dịch không nhỉ? Em thấy nó khá giống với `Dense`, `MaxPool`, etc.

**Comment by duythanhvn** [comment]
Hm.. anh cũng thấy vậy.

**Comment by davidnvq** [comment]
@rootonchair Phần 1 resnet mang mình tới đây :)) Hồi học đh, mình thấy từ `class` dịch là lớp quen thuộc hơn. Và `function` trong trường hợp này thì dịch là `hàm số` có lẽ sẽ đỡ bị lẫn với `hàm` trong ngôn ngữ lập trình.

**Comment by minhduc0711** [comment]
@davidnvq hmm từ `class` thì mình cũng k rõ nên no comment. Còn `function` thì còn có context ở đoạn văn xung quanh ảnh mà, mình nghĩ k sao đâu.

**Comment by duythanhvn** [comment]
> @rootonchair Phần 1 resnet mang mình tới đây :)) 

Cách comment này quen lắm này... Hm.. ông giáo có hay comment dạo trên Youtube không :)))

**Comment by davidnvq** [comment]
Em không bh cmt trên youtube luôn :)) may mà @rootonchair mention nó ở PR kia nên có cái để thảo luận trước khi close PR kia :))

**Comment by lkhphuc** [comment]
👍 
`generic function classes: các lớp hàm tổng quát`
`nested function classes: các lớp hàm lồng nhau`.

**Comment by rootonchair** [comment]
Đã fix. Mình sẽ bắt đầu đưa vào hình. Thanks mọi người
