### ISSUE TITLE
Revise "lenet_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#1423]
Phần này được dịch bởi:
* **tranyenthy**
* **dacdinh147**

Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by davidnvq** [comment]
Người mới tham gia chưa được revise hả anh @duythanhvn ?

**Comment by duythanhvn** [comment]
@davidnvq Đừng vội, mình sẽ thông tin cho bạn ngay khi được nhé 😄 Trong thời gian đó, nếu bạn có thời gian thì bạn có thể tham gia review những phần nội dung (không phải do bạn dịch) trong phase 1 của những bạn dịch khác.

Trong 4 phần bạn review trước đó, các thành viên khác đã có phản hồi với bạn để giúp cho việc review dễ hơn và phù hợp hơn với cách hoạt động của dự án. Không biết bạn đã xem chưa? Nhưng cứ bắt đầu như thế đã nhé. 😄

**Comment by davidnvq** [comment]
À em xem rồi a Thanh 👍 vậy là review có thể vào trực tiếp pull request mà không cần đăng ký anh nhỉ?

**Comment by davidnvq** [comment]
a xoá cmt giúp em nhé :))
