### ISSUE TITLE
Revise "vgg_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#1474]
Phần này được dịch bởi: **quangnhat185**

Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by cuongvng** [comment]
@duythanhvn em nhận #1474 và #1475 ạ.

**Comment by duythanhvn** [comment]
Comment vào từng Issue anh mới assign cho em được Cường nha.
