### ISSUE TITLE
Dịch hình chương RNN

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#1483]
Các hình cần dịch:
* [sequence-model.svg](https://github.com/aivivn/d2l-vn/blob/master/img/sequence-model.svg)
* [rnn.svg](https://github.com/aivivn/d2l-vn/blob/master/img/rnn.svg)
* [rnn-train.svg](https://github.com/aivivn/d2l-vn/blob/master/img/rnn-train.svg)

Xem hướng dẫn dịch hình ảnh tại [đây](https://github.com/aivivn/d2l-vn/blob/master/img/README.md)

**Comment by rootonchair** [comment]
| Tiếng Anh | Tiếng Việt | Hình |
| :---: | :---: | :---: |
| hidden state | trạng thái ẩn | |
| output state | trạng thái đầu ra | `rnn-train.svg` |

Mình tính giữ nguyên từ "copy" trong `rnn.svg` và "Time machine by H. G." trong `train-rnn.svg` chắc ổn nhỉ?
cc: @minhduc0711 @lkhphuc @duythanhvn @davidnvq

**Comment by duythanhvn** [comment]
Yep, ổn em.
