### ISSUE TITLE
Dịch hình chương Modern RNN - Phần 1

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#1610]
Các hình cần dịch:
* [gru_1.svg](https://github.com/aivivn/d2l-vn/blob/master/img/gru_1.svg)
* [gru_2.svg](https://github.com/aivivn/d2l-vn/blob/master/img/gru_2.svg)
* [gru_3.svg](https://github.com/aivivn/d2l-vn/blob/master/img/gru_3.svg)
* [lstm_0.svg](https://github.com/aivivn/d2l-vn/blob/master/img/lstm_0.svg)
* [lstm_1.svg](https://github.com/aivivn/d2l-vn/blob/master/img/lstm_1.svg)
* [lstm_2.svg](https://github.com/aivivn/d2l-vn/blob/master/img/lstm_2.svg)
* [lstm_3.svg](https://github.com/aivivn/d2l-vn/blob/master/img/lstm_3.svg)

Xem hướng dẫn dịch hình ảnh tại [đây](https://github.com/aivivn/d2l-vn/blob/master/img/README.md)

**Comment by cuongvng** [comment]
@rootonchair cho mình thử dịch và edit mấy hình này xem.

**Comment by rootonchair** [comment]
@cuongvng Chào mừng đến với team culi :))
Có khó khăn gì thì cứ nói mình nhé. Trước tiên bạn đề xuất những từ cần dịch vào issue này giúp mình.

**Comment by cuongvng** [comment]
@rootonchair xem dịch thế này ổn chưa giúp mình nhé. Có gì thảo luận ở #1632 nữa.

| **Tiếng Anh** | **Tiếng Việt** |
| Hidden state | Trạng thái ẩn |
| Reset gate | Cổng xoá |
| Update gate | Cổng cập nhật |
| Input | Đầu vào |
| FC layer with activation function | Tầng kết nối đầy đủ với hàm kích hoạt |
| Copy | Sao chép |
| Concatenate | Nối |
| Candidate hidden state | Trạng thái ẩn ứng viên |
| Elementwise operator | Phép toán theo từng phần tử |
| Memory | Bộ nhớ |
| Forget gate | Cổng quên |
| Input gate | Cổng đầu vào |
| Output gate | Cổng đầu ra |
| Candidate memory | Bộ nhớ ứng viên |

**Comment by rootonchair** [comment]
@cuongvng bạn update lại nhé

**Comment by cuongvng** [comment]
@rootonchair đã update. Review lại giúp mình nhé.

**Comment by rootonchair** [comment]
@cuongvng `concatenate` mình dịch là `Ghép nối` để thống nhất với các chương trước nhé. `reset` mà dịch là `xóa` thì hơi sai nghĩa.

@lkhphuc @minhduc0711 : mình cần thêm trợ giúp khoản `reset gate` này

**Comment by duythanhvn** [comment]
Reset anh thường dùng là `đặt lại` (trong cài đặt lại, đưa về trạng thái ban đầu).

**Comment by cuongvng** [comment]
hm từ [1](https://d2l.ai/chapter_recurrent-modern/gru.html)
>For instance, a reset variable would allow us to control how much of the previous state we might still want to remember
và [2](https://towardsdatascience.com/understanding-gru-networks-2ef37df6c9be)
>2. Reset gate
Essentially, this gate is used from the model to decide how much of the past information to forget.

mình thấy có thể dịch `reset` là `xoá` hoặc `quên`. Vì ở LSTM có `forget gate` là `cổng quên` rồi nên mình đề xuất dịch `reset` là `xoá`, xoá thông tin cũ không cần thiết.

**Comment by lkhphuc** [comment]
Chỗ này mình thấy `cổng xoá` cũng đúng nghĩa, `cổng đặt lại` nghe không hay mà cũng ko rõ nghĩa hơn `cổng xoá`.

**Comment by rootonchair** [comment]
Okie, cá nhân mình thì `xóa` và `quên` lại na ná nhau. @cuongvng bạn có thể bắt đầu edit hình nhé

**Comment by cuongvng** [comment]
okie

**Comment by davidnvq** [comment]
đồng ý với @rootonchair  xoá với quên nghe giống nhau phết.

**Comment by davidnvq** [comment]
Nhân tiện giờ mới để ý từ `memory` dịch là `ký ức` à, nghe văn học thế. Rồi có từ `Memory Cell` chắc dịch là `Đơn vị Bộ nhớ` cho sát nghĩa với `LSTM`?

**Comment by duythanhvn** [comment]
@davidnvq nhóm toàn nhà văn mà ông giáo đùa....

**Comment by minhduc0711** [comment]
discussion ở nhiều nơi quá :))) chắc lần sau phải mở PR thảo luận glossary rồi hẵng quay lại đây sau nhỉ
