### ISSUE TITLE
Dịch hình chương Modern RNN - Phần 2

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#1611]
Các hình cần dịch:
* [encoder-decoder.svg](https://github.com/aivivn/d2l-vn/blob/master/img/encoder-decoder.svg)
* [seq2seq.svg](https://github.com/aivivn/d2l-vn/blob/master/img/seq2seq.svg)
* [seq2seq-details.svg](https://github.com/aivivn/d2l-vn/blob/master/img/seq2seq-details.svg)
* [seq2seq_predict.svg](https://github.com/aivivn/d2l-vn/blob/master/img/seq2seq_predict.svg)
* [s2s-prob1.svg](https://github.com/aivivn/d2l-vn/blob/master/img/s2s-prob1.svg)
* [s2s-prob2.svg](https://github.com/aivivn/d2l-vn/blob/master/img/s2s-prob2.svg)
* [beam-search.svg](https://github.com/aivivn/d2l-vn/blob/master/img/beam-search.svg)

Xem hướng dẫn dịch hình ảnh tại [đây](https://github.com/aivivn/d2l-vn/blob/master/img/README.md)

**Comment by nguyenhoa93** [comment]
Mình xin phép tự assign dịch phần này.

**Comment by duythanhvn** [comment]
> Mình xin phép tự assign dịch phần này.

@nguyenhoa93: Bạn có thể xử lý hình ảnh chứ? Trước tiên bạn đề xuất những từ cần dịch vào issue này giúp mình đã nhé.

**Comment by nguyenhoa93** [comment]
> > Mình xin phép tự assign dịch phần này.
> 
> @nguyenhoa93: Bạn có thể xử lý hình ảnh chứ? Trước tiên bạn đề xuất những từ cần dịch vào issue này giúp mình đã nhé.

File `svg` này edit cũng tiện nên mình nghĩ mình làm được. Mình sẽ comment phần dịch vào issue này trước khi bắt đầu edit như trong [hướng dẫn](https://github.com/aivivn/d2l-vn/blob/master/img/README.md)

**Comment by nguyenhoa93** [comment]
Mình gửi phần dịch các ảnh trong issue nay, mong mọi người review giúp:

|        Tiếng Anh        |             Tiếng Việt            |                                      Từ Ảnh                                      |
|:-----------------------:|:---------------------------------:|:--------------------------------------------------------------------------------:|
| Input                   | Đầu vào                           | encoder-decoder.svg                                                              |
| Encoder                 | Bộ mã hoá                         | encoder-decoder.svg<br>seq2seq.svg<br>seq2seq-details.svg<br>seq2seq_predict.svg |
| State                   | Trạng thái                        | encoder-decoder.svg                                                              |
| Decoder                 | Bộ giải mã hoá                    | encoder-decoder.svg<br>seq2seq.svg<br>seq2seq-details.svg<br>seq2seq_predict.svg |
| Output                  | Đầu ra                            | encoder-decoder.svg                                                              |
| hidden state            | trạng thái ẩn                     | seq2seq.svg<br>seq2seq_predict.svg                                               |
| Sources                 | Nguồn                             | seq2seq-details.svg                                                              |
| Embedding               | Embedding                         | seq2seq-details.svg                                                              |
| Recurrent layer         | Tầng truy hồi                     | seq2seq-details.svg                                                              |
| Targets                 | Mục tiêu                          | seq2seq-details.svg                                                              |
| Dense                   | Tầng kết nối dày đặc              | seq2seq-details.svg                                                              |
| Timestep                | Bước thời gian                    | s2s-prob1.svg<br>s2s-prob2.svg                                                   |
| Timestep {i} Candidates | Các ưng viên ở bước thời gian {i} | beam-search.svg                                                                  |

**Comment by lkhphuc** [comment]
Để đối xứng cho đẹp thì mình đề xuất encoder-decoder là `bộ ghi mã - bộ giải mã`. #1674

**Comment by duythanhvn** [comment]
Timestep {i} Candidates có thể dịch là "**Những tiềm năng tại bước thời gian {i}**" không anh em nhỉ?

**Comment by cuongvng** [comment]
hm em nghĩ theo ngữ cảnh phần đó thì `tiềm năng` không đủ nghĩa bằng `ứng viên`.
>For each subsequent timestep, we are going to select the $k$ output sequences with the highest conditional probability from the total of $k\left|\mathcal{Y}\right|$ possible output sequences based on the $k$ candidate output sequences from the previous timestep.
These will be the candidate output sequences for that timestep.

**Comment by nguyenhoa93** [comment]
Cảm ơn góp ý của mọi người. Mình sẽ sửa `Encoder - Decoder` thành `Bộ ghi mã - Bộ giải mã` như góp ý của @lkhphuc và vẫn giữ nguyên `ứng viên` thay vì `tiềm năng`. Mọi người còn góp ý gì thêm nữa không ạ? Nếu không mình sẽ bắt đầu edit ảnh.

**Comment by cuongvng** [comment]
@nguyenhoa93 ah chờ resolve `Encoder - Decoder` trong #1674 đã. Mọi người đang nghiêng về `bộ mã hoá` -`bộ giải mã`.

**Comment by rootonchair** [comment]
Hi @nguyenhoa93 , bạn có thể bắt đầu đưa các từ được dịch vào hình. Thanks bạn
