### ISSUE TITLE
Dịch hình chương Attention Mechanisms - Phần 1

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#1612]
Các hình cần dịch:
* [attention.svg](https://github.com/aivivn/d2l-vn/blob/master/img/attention.svg)
* [attention_output.svg](https://github.com/aivivn/d2l-vn/blob/master/img/attention_output.svg)
* [seq2seq_attention.svg](https://github.com/aivivn/d2l-vn/blob/master/img/seq2seq_attention.svg)
* [seq2seq-attention-details.svg](https://github.com/aivivn/d2l-vn/blob/master/img/seq2seq-attention-details.svg)

Xem hướng dẫn dịch hình ảnh tại [đây](https://github.com/aivivn/d2l-vn/blob/master/img/README.md)

**Comment by rootonchair** [comment]
Note: `seq2seq-attention.svg` có lỗi typo (content -> context) https://github.com/d2l-ai/d2l-en/pull/882

**Comment by nguyenhoa93** [comment]
@duythanhvn bạn assign mình phần này nhé!

**Comment by duythanhvn** [comment]
@nguyenhoa93 Bạn có thể tự assign nhé, mình chỉ cần bạn tag vào thông báo để mình nắm là được rồi nghen. Ví dụ ở những phần dịch, bạn muốn dịch 3 phần, thì comment mình biết là bạn sẽ lấy 3 phần (1-2-3 chẳng hạn); rồi tự assign, thế là được rồi nghen.

**Mẹo cho bạn:** bạn có thể ở phần issue, chọn các phần cần nhận, rồi chọn assign ở đây, bạn sẽ chỉ cần làm 1 lần cho những phần muốn nhận.
<img width="1327" alt="Screen Shot 2020-06-06 at 23 47 17" src="https://user-images.githubusercontent.com/8481767/83949820-10bea100-a850-11ea-820e-e4956d4a695c.png">

**Comment by nguyenhoa93** [comment]
À, mình tự assign được nhưng ở issue #1690 bạn có nói là thông báo với bạn trước nên mình nhắn. :")

**Comment by duythanhvn** [comment]
Đúng rồi, chỉ cần nhắn (tag) thông báo thôi nghen :))) Thông báo xong thì... tự xử được rồi nè :)))

**Comment by nguyenhoa93** [comment]
Hình `seq2seq-attention.svg` có 2 chỗ chỉnh sửa:
1. content --> context
2. Đầu ra của decoder bị nhầm thành `Enc_Outputs` --> `Dec_Outputs`

|     Tiếng Anh     |          Tiếng Việt         |                                              Từ Ảnh                                             |
|:-----------------:|:---------------------------:|:-----------------------------------------------------------------------------------------------:|
| Memory            | Bộ nhớ                      | attention.svg                                                                                   |
| Keys              | Từ khoá                     | attention.svg<br>attention_output.svg<br>seq2seq_attention.svg                                  |
| Values            | Giá trị                     | attention.svg<br>attention_output.svg<br>seq2seq_attention.svg                                  |
| Attention         | Tầng tập trung              | attention.svg<br>attention_output.svg<br>seq2seq_attention.svg<br>seq2seq-attention-details.svg |
| Query             | Truy vấn                    | attention.svg<br>attention_output.svg                                                           |
| Output            | Đầu ra                      | attention.svg<br>attention_output.svg                                                           |
| Attention weights | Trọng số của tầng tập trung | attention_output.svg                                                                            |
| Encoder           | Bộ mã hoá                   | seq2seq_attention.svg<br>seq2seq-attention-details.svg                                          |
| Hidden state      | Trạng thái ẩn               | seq2seq_attention.svg                                                                           |
| Enc_outputs       | Đầu ra của bộ mã hoá        | seq2seq_attention.svg                                                                           |
| Context           | Ngữ cảnh                    | seq2seq_attention.svg                                                                           |
| Decoder           | Bộ giải mã                  | seq2seq_attention.svg<br>seq2seq-attention-details.svg                                          |
| Dec_outputs       | Đầu ra của bộ giải mã       | seq2seq_attention.svg                                                                           |
| Sources           | Nguồn                       | seq2seq-attention-details.svg                                                                   |
| Embedding         | Embedding                   | seq2seq-attention-details.svg                                                                   |
| Recurrent layer   | Tầng truy hồi               | seq2seq-attention-details.svg                                                                   |
| Dense             | Tầng kết nối dày đặc        | seq2seq-attention-details.svg                                                                   |
| Targets           | Mục tiêu                    | seq2seq-attention-details.svg                                                                   |

**Comment by rootonchair** [comment]
Thanks @nguyenhoa93 , bạn có thể bắt đầu đưa bản dịch vô hình ảnh
