### ISSUE TITLE
Dịch hình chương Attention Mechanisms - Phần 2

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#1613]
Các hình cần dịch:
* [transformer.svg](https://github.com/aivivn/d2l-vn/blob/master/img/transformer.svg)
* [self-attention.svg](https://github.com/aivivn/d2l-vn/blob/master/img/self-attention.svg)
* [multi-head-attention.svg](https://github.com/aivivn/d2l-vn/blob/master/img/multi-head-attention.svg)
* [positional_encoding.svg](https://github.com/aivivn/d2l-vn/blob/master/img/positional_encoding.svg)
* [self-attention-predict.svg](https://github.com/aivivn/d2l-vn/blob/master/img/self-attention-predict.svg)

Xem hướng dẫn dịch hình ảnh tại [đây](https://github.com/aivivn/d2l-vn/blob/master/img/README.md)

**Comment by nguyenhoa93** [comment]
@duythanhvn bạn assign mình phần này nhé!

**Comment by nguyenhoa93** [comment]
Phần này có nhiều thuật ngữ cần phải thảo luận để  đưa vào `glossary.md`. Nhờ mọi người review.

|          Tiếng Anh          |                Tiếng Việt               |                                    Từ Ảnh                                    |
|:---------------------------:|:---------------------------------------:|:----------------------------------------------------------------------------:|
| Transformer                 | Transformer                             | transformer.svg                                                              |
| Seq2seq with Attention      | Chuỗi sang chuỗi với cơ chế tập trung   | transformer.svg                                                              |
| Sources                     | Nguồn                                   | transformer.svg                                                              |
| Embedding                   | Embedding                               | transformer.svg                                                              |
| Recurrent layer             | Tầng truy hồi                           | transformer.svg                                                              |
| Attention                   | Tầng tập trung                          | transformer.svg<br>multi-head-attention.svg                                  |
| Encoder                     | Bộ mã hoá                               | transformer.svg                                                              |
| Decoder                     | Bộ giải mã                              | transformer.svg                                                              |
| Dense                       | Tầng kết nối dày đặc                    | transformer.svg<br>multi-head-attention.svg                                  |
| Targets                     | Mục tiêu                                | transformer.svg                                                              |
| Positional encoding         | Mã hoá vị trí                           | transformer.svg                                                              |
| Multi-head attention        | Tầng tập trung đa đầu                   | transformer.svg                                                              |
| Add & norm                  | Cộng và chuẩn hoá                       | transformer.svg                                                              |
| Position-wise FFN           | Mạng lan truyền thuận định hướng vị trí | transformer.svg                                                              |
| State                       | Trạng thái                              | transformer.svg                                                              |
| Masked multi-head attention | Tầng tập trung đa đầu có mặt nạ         | transformer.svg                                                              |
| Inputs                      | Đầu vào                                 | self-attention.svg                                                           |
| Outputs                     | Đầu ra                                  | self-attention.svg<br>self-attention-predict.svg                             |
| Query                       | Truy vấn                                | self-attention.svg<br>multi-head-attention.svg<br>self-attention-predict.svg |
| Key                         | Từ khoá                                 | self-attention.svg<br>multi-head-attention.svg<br>self-attention-predict.svg |
| Value                       | Giá trị                                 | self-attention.svg<br>multi-head-attention.svg<br>self-attention-predict.svg |
| Self-attention              | Tầng tự tập trung                       | self-attention.svg<br>self-attention-predict.svg                             |
| Concat                      | Ghép                                    | multi-head-attention.svg                                                     |
| Embedding size              | Kích thước embedding                    | positional_encoding.svg                                                      |
| Sequence length             | Độ dài chuỗi                            | positional_encoding.svg                                                      |
| Input sequence matrix       | Ma trận chuỗi đầu vào                   | positional_encoding.svg                                                      |
| Positional encoding matrix  | Ma trận mã hoá vị trí                   | positional_encoding.svg                                                      |

**Comment by duythanhvn** [comment]
Từ nào bạn thấy cần đưa vào Bảng thuật ngữ thì bạn mở PR để thảo luận nhé, mỗi PR thảo luận thuật ngữ chỉ nên có từ 1-2 thuật ngữ. 

Ở phần Issue dịch ảnh, mình khuyến khích chỉ để chốt nhanh những từ đã thảo luận, từ có sẵn trong bảng thuật ngữ và từ phổ biến không cần thảo luận thôi hen.

**Comment by lkhphuc** [comment]
`Seq2seq with Attention | Chuỗi sang chuỗi với cơ chế tập trung` -> `Chuỗi sang chuỗi có tập trung`.

MÌnh thấy mấy từ `Dense, Attention, Multihead attention` ở trong ô chữ nhật là hàm ý layer, mình có thể không cần viết thêm chữ `Tầng ...` vào đằng trước cũng được, một phần cũng là sợ dài quá không đủ chỗ trong ô. cc @minhduc0711 .

**Comment by rootonchair** [comment]
Đồng ý với @lkhphuc , @nguyenhoa93 bạn edit bảng lại nhé

**Comment by nguyenhoa93** [comment]
@lkhphuc ở bên glossary bạn góp ý như về `multi-head attention` nên được dịch là `tập trung đa nhánh` ở đây: https://github.com/aivivn/d2l-vn/pull/1771#discussion_r438363222.
Nhờ bạn vào cho ý kiến trước khi mình bắt đầu edit ảnh nhé!

@rootonchair ok, mình sẽ lược bỏ từ `tầng`.
