### ISSUE TITLE
Glossary "ground truth"

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/d2l-vn#166]
Từ này có lẽ ai cũng hiểu nhưng chưa biết dịch thế nào.

**Comment by samthehai** [comment]
Lúc đầu mình đồng ý dịch thành `chân trị`, nhưng sau đó xem xét lại thì bởi vì ground truth có thể không phải lúc nào cũng phản ánh đúng sự thật (ví dụ như cách đo đạc lấy mẫu bị sai). Nên là mình đề xuất dịch `ground truth` thành `chân trị nền` (hoặc là `chân trị gốc` ).

**Comment by lkhphuc** [comment]
https://github.com/aivivn/d2l-vn/pull/146#discussion_r358591317 link thảo luận liên quan cho mọi người, mình copy vô đây cho dễ theo dõi:

> @tiepvupsu:
 ""ground truth" không thể dịch là "cơ sở thực tế" được. Nghĩa của từ này là giá trị chính xác của nhãn.
Mình chợ nhớ đến "bảng chân trị" (the truth table) được dùng trong các hàm logic (AND, NOT, OR, XOR). Phải chăng mình nên dùng từ "chân trị" để thay cho "ground truth"?"

> @lkhphuc:
 "chân trị" nghe khá hay, nhưng chính xác hay không thì em không có ý kiến. Chờ mọi người.

> @william-vu: 
@tiepvupsu : theo e hiểu thì "chân trị" là giá trị chân lý; 1 ví dụ: giá trị chân lý của một mệnh đề có thể đúng hoặc sai (e nhớ sách lớp 10 nói thế) --> có vẻ chưa phù hơp khi dịch "ground truth" thành "chân trị".
Update: sau khi nghĩ kĩ thì e cũng ko biết là đúng hay sai. Có thể dịch là "giá trị thật của nhãn" ko bác?

> @tiepvupsu:
  ""_Update: sau khi nghĩ kĩ thì e cũng ko biết là đúng hay sai. Có thể dịch là "giá trị thật của nhãn" ko bác?_""
  Theo một số tài liệu thì nó chính là "nhãn" chứ không cần phải ghi "thật của nhãn" nữa. Em muốn một từ ngắn gọn hơn một chút.
Có phần này quan trọng có lẽ mình cũng lưu ý khi dịch:
   "" _Ground truth can be wrong. It is a measurement, and there can be errors in it. In some ML scenarios it can also be a subjective measurement where it is difficult define an underlying objective truth - e.g. expert opinion or analysis, which you are hoping to automate. Any ML model you train will be limited by the quality of the ground truth used to train and test it, and that is part of the explanation on the Wikipedia quote. It is also why published articles about ML should include full descriptions of how the data was collected._""
Nguồn: https://datascience.stackexchange.com/a/17840

@nmdang:
> Mình thấy wikipedia có viết thế này:
    "_Ground truth is a term used in various fields to refer to information provided by direct observation (i.e. empirical evidence) as opposed to information provided by inference._"
Nếu muốn nhấn mạnh vào ý "empirical evidence" thì mình cũng có thể dịch ground truth (tính từ) thành "quan trắc". Tỷ dụ ground truth data là dữ liệu quan trắc, ground truth label --> nhãn quan trắc

**Comment by ngcthuong** [comment]
> hmm. Ground truth như mình dùng bên mình thường theo nghĩa là "gốc". Ảnh gốc, ảnh chưa qua chỉnh sửa chưa bị suy hao các thứ.
> 
> Còn các từ ở trên thì mình thấy "trân trị", thì tớ cùng quan điểm với @william-vu. Quan trắc thì giống từ liên quan tới đo đạc hơn, cảm giác không khái quát cho tất cả các trường hợp được.
> Đặt thử các từ khác như Ground truth image ---> ảnh quan trắc thì nghe nó ra từ khác rồi.
> 
> Vậy từ 'Nhãn gốc' thì sao nhỉ?
> 
> Cảm giác là nhãn chưa bị chỉnh sửa, vẫn thấy hơi gợi gợn tí.
