### ISSUE TITLE
Revise "rnn-gluon_vn"

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#1689]
Phần này được dịch bởi: **cuongvng**
Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by duythanhvn** [comment]
cc: @rootonchair @minhduc0711

**Comment by rootonchair** [comment]
Em xin nhận phần này

**Comment by cuongvng** [comment]
Có gì đó sai sai, phần em dịch là `rnn-gluon_vn` mà @duythanhvn

**Comment by duythanhvn** [comment]
My bad. @rootonchair đã revise chưa nhỉ?

**Comment by rootonchair** [comment]
Chưa nha anh
