### ISSUE TITLE
Dịch "encoder-decoder_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#1690]
Phần cần dịch: https://github.com/aivivn/d2l-vn/blame/master/chapter_recurrent-modern/encoder-decoder_vn.md#L1-L90

### Hướng dẫn
- [Dịch trực tiếp trên website](https://github.com/aivivn/d2l-vn/blob/master/CONTRIBUTING.md).
- Sau khi nhấn vào phần cần dịch ở trên, hãy chọn **Normal view** và làm theo hướng dẫn ở trên để có thể bắt đầu dịch.

![](https://raw.githubusercontent.com/aivivn/d2l-vn/master/translation_team/normal-view.png)

**Comment by duythanhvn** [comment]
@nguyenhoa93 Bạn giúp mình trong những lần tới trước khi self-assigned thì comment thông báo giúp mình nhé.

**Comment by nguyenhoa93** [comment]
Vâng, để lần sau mình nhắn. Mình làm theo hướng dẫn không có phần này, có gì bạn cập nhật lại trong file để mọi người làm theo cho tiện.
