### ISSUE TITLE
Dịch "encoder-decoder_vn" - Phần 2

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#1691]
Phần cần dịch: https://github.com/aivivn/d2l-vn/blame/master/chapter_recurrent-modern/encoder-decoder_vn.md#L92-L153

### Hướng dẫn
- [Dịch trực tiếp trên website](https://github.com/aivivn/d2l-vn/blob/master/CONTRIBUTING.md).
- Sau khi nhấn vào phần cần dịch ở trên, hãy chọn **Normal view** và làm theo hướng dẫn ở trên để có thể bắt đầu dịch.

![](https://raw.githubusercontent.com/aivivn/d2l-vn/master/translation_team/normal-view.png)

**Comment by duythanhvn** [comment]
@nguyenhoa93 Hai phần này không biết khi nào lên được bạn nhỉ?

**Comment by duythanhvn** [comment]
@nguyenhoa93 Xin lỗi bạn, ở https://github.com/aivivn/d2l-vn/pull/1723 mình có vẻ truyền đạt chưa đủ thông tin cho bạn. Ở PR đó, mình có hai thông tin:
- PR cho phần hình ảnh chỉ cần điền Close #issue-number. Không cần gì thêm.
- Tên của PR thì copy y nguyên từ Issue sang, không để số Issue trên tên PR vì không có tác dụng gì.

Còn với phần dịch thì làm theo PR template đã có sẵn. Ý mình chỉ lưu ý ở chỗ đặt số Issue cho có tính năng thôi. Xin lỗi bạn mình truyền đạt chưa đủ thông tin cho bạn. Các PR mới của bạn, mình đã thay đổi lại nội dung description giúp bạn. 

Nếu bạn có chưa rõ gì thì phản hồi giúp mình nhé. Cảm ơn bạn.

**Comment by nguyenhoa93** [comment]
> @nguyenhoa93 Xin lỗi bạn, ở #1723 mình có vẻ truyền đạt chưa đủ thông tin cho bạn. Ở PR đó, mình có hai thông tin:
> 
> * PR cho phần hình ảnh chỉ cần điền Close #issue-number. Không cần gì thêm.
> * Tên của PR thì copy y nguyên từ Issue sang, không để số Issue trên tên PR vì không có tác dụng gì.
> 
> Còn với phần dịch thì làm theo PR template đã có sẵn. Ý mình chỉ lưu ý ở chỗ đặt số Issue cho có tính năng thôi. Xin lỗi bạn mình truyền đạt chưa đủ thông tin cho bạn. Các PR mới của bạn, mình đã thay đổi lại nội dung description giúp bạn.
> 
> Nếu bạn có chưa rõ gì thì phản hồi giúp mình nhé. Cảm ơn bạn.

Cảm ơn bạn. Mình sẽ lưu ý. Ở bên kia mình đọc vội nên tưởng PR sẽ ngắn gọn như vậy. :v
