### ISSUE TITLE
Tổng hợp lỗi chương 8 - RNN trước khi công bố

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/d2l-vn#1803]
https://d2l.aivivn.com/chapter_recurrent-neural-networks/index_vn.html

**Comment by duythanhvn** [comment]
Đang có hai mục chương 7 trên website luôn anh ạ.

**Comment by duythanhvn** [comment]
<img width="1059" alt="Screen Shot 2020-06-14 at 07 57 32" src="https://user-images.githubusercontent.com/8481767/84582318-b788db80-ae14-11ea-94cd-77f1ee1dcf1d.png">

**Comment by duythanhvn** [comment]
hoá (hóa).

<img width="1089" alt="Screen Shot 2020-06-14 at 08 07 37" src="https://user-images.githubusercontent.com/8481767/84582437-20248800-ae16-11ea-87c7-9eefef012b1b.png">
$ 1/5 $

**Comment by duythanhvn** [comment]
<img width="1248" alt="Screen Shot 2020-06-14 at 08 08 57" src="https://user-images.githubusercontent.com/8481767/84582449-4e09cc80-ae16-11ea-9192-4d9e4010ab6a.png">
từ dừng (stop word)

**Comment by duythanhvn** [comment]
<img width="1068" alt="Screen Shot 2020-06-14 at 08 10 00" src="https://user-images.githubusercontent.com/8481767/84582464-74c80300-ae16-11ea-9363-4d5444b7c883.png">
:numref: | fig_timemachine_5gram

**Comment by tiepvupsu** [comment]
> <img alt="Screen Shot 2020-06-14 at 08 08 57" width="1248" src="https://user-images.githubusercontent.com/8481767/84582449-4e09cc80-ae16-11ea-9192-4d9e4010ab6a.png">
> 
> từ dừng (stop word)

~do~đó

**Comment by duythanhvn** [comment]
<img width="1092" alt="Screen Shot 2020-06-14 at 08 21 22" src="https://user-images.githubusercontent.com/8481767/84582587-0b48f400-ae18-11ea-9e98-4a03c31ec7f8.png">

**Comment by duythanhvn** [comment]
<img width="1251" alt="Screen Shot 2020-06-14 at 08 23 59" src="https://user-images.githubusercontent.com/8481767/84582615-67ac1380-ae18-11ea-92ff-167c6a75d268.png">

**Comment by duythanhvn** [comment]
<img width="1083" alt="Screen Shot 2020-06-14 at 08 26 36" src="https://user-images.githubusercontent.com/8481767/84582632-c5d8f680-ae18-11ea-80b3-815b11d783c3.png">
"cách mạng"

**Comment by duythanhvn** [comment]
<img width="1215" alt="Screen Shot 2020-06-14 at 08 27 20" src="https://user-images.githubusercontent.com/8481767/84582642-e7d27900-ae18-11ea-99ec-78fc65742321.png">
`Ta có thể tính phần đầu tiên và phần thứ hai của đạo hàm môt cách dễ dàng`

**Comment by duythanhvn** [comment]
<img width="1080" alt="Screen Shot 2020-06-14 at 08 29 14" src="https://user-images.githubusercontent.com/8481767/84582661-236d4300-ae19-11ea-8f06-0322b5b47b64.png">

**Comment by rootonchair** [comment]
![image](https://user-images.githubusercontent.com/23548268/84584666-41df3880-ae31-11ea-9a97-fefcadeafe67.png)
