### ISSUE TITLE
Revise "gru_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#1819]
Phần này được dịch bởi:
* **tamio96**
* **nguyenduydu**
* **davidnvq**

Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by cuongvng** [comment]
@duythanhvn em nhận 2 phần GRU ạ.

**Comment by duythanhvn** [comment]
Chờ mãi.
