### ISSUE TITLE
Revise "deep-rnn_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#1835]
Phần này được dịch bởi: **davidnvq**
Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by duythanhvn** [comment]
Các phần này có thể lên trong cuối tuần này chứ ông giáo hen?

**Comment by quangnhat185** [comment]
Tối nay sẽ lên hết nhé :ok_man:
