### ISSUE TITLE
Add chương "Tools for Deep Learning" về dự án

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#199]
- [x] Lấy chương "Tools for Deep Learning" về.
- [x] Cập nhật tệp labeler.yml

**Comment by tiepvupsu** [comment]
@duythanhvn theo Thứ tự dịch ở trang chủ của repo này thì mình sẽ làm phần Tools này sau. Phần https://d2l.ai/chapter_preliminaries/index.html sẽ được làm trước.

Hoặc có một options khác là tách ra hai team, một team dịch chương Tools này trong khi team kia vẫn dịch các chương khác.

Cũng xin lưu ý là mình nên đến đâu xong đến đó, không nên dàn trải nhiều chương quá. Hiện cũng đã có khá nhiều PR đã ở trong hệ thống khá lâu, mình tập trung hoàn thiện các PR đó trước.

**Comment by duythanhvn** [comment]
Em để đây để remind thôi ạ, sẽ ưu tiên theo thứ tự trước ạ. Em có chút nhầm lẫn về phần Install và Preliminaries. Mình cứ ưu tiên xong từng giai đoạn đi anh, nhân sự mình đang mỏng, không nên chia team.

**Comment by tiepvupsu** [comment]
Okie, xong phần Introduction anh sẽ công bố rồi kêu gọi thêm người vào ủng hộ.

Nhân tiện, hôm trước trên fb có một bạn nói về việc [sử dụng smartcart](https://www.facebook.com/groups/machinelearningcoban/permalink/827945820996160/?comment_id=834521397005269&reply_comment_id=842241896233219) cho việc dịch sẽ dễ dàng hơn. Anh chưa có thời gian xem cái này, nếu em có thời gian thì ghé qua trang này xem flow có lợi cho mình hơn không.

Mặc dù github đang rất tốt, anh cũng đang thấy một số bạn chưa quen dùng nên mình không thu hút được nhiều người.

**Comment by duythanhvn** [comment]
Vâng, em sẽ xem qua smartcart, em cũng đang xem qua một cái tool khác vì thấy smartcart đang có chi phí, để em test một thời gian rồi sẽ báo anh biết thêm ạ.
