### ISSUE TITLE
Dịch chữ tại file book-org.svg

### ISSUE THREAD

**Issue by quangnhat185** [aivivn/d2l-vn#202]
Issue này được mở để thảo luận về cách dịch chữ tại file `book-org.svg`. Dưới đây là ảnh gốc và bảng dịch chữ tạm thời, mọi người có góp ý gì về cách dịch thì để lại comment phía dưới nhé.

![image](https://user-images.githubusercontent.com/41325216/71358263-b2934f80-2588-11ea-84df-2e5ed9810077.png)

<br/>
<br/>
<br/>

|Thứ tự|Tiếng Anh| Tiếng Việt|
|:--:| :---: | :---: | 
|1| Introduction | Giới Thiệu |
|2| Preliminaries | ~Tổng Quan~ Sơ bộ |
|3| Linear Neural Networks | Mạng Nơ-ron Tuyến Tính |
|4| Multilayer Perceptrons | Perceptron Đa ~Lớp~ Tầng |
|5| Deep Learning Computation | Tính Toán Học Sâu |
|6| Convolutional Neural Networks | Mạng Nơ-ron Tích Chập |
|7| Modern Convolutional Networks | Mạng Tích Chập Hiện Đại |
|8| Recurrent Neural Networks | Mạng Nơ-ron Truy Hồi |
|9| Modern Recurrent Networks | Mạng Truy Hồi Hiện Đại |
|10| Attention Mechanisms | Cơ Chế Tập Trung |
|11| Optimization Algorithms | Thuật Toán Tối Ưu |
|12| Computational Performance| Hiệu Năng Tính Toán |
|13| Computer Vision | Thị Giác Máy Tính |
|14| Natural Language Processing | Xử Lý Ngôn Ngữ Tự Nhiên |

#183

**Comment by rootonchair** [comment]
"Multilayer Perceptrons" -> "Perceptron Đa Tầng"

**Comment by tiepvupsu** [comment]
Từ "performance" trong trường hợp này lại được dịch là "hiệu năng" em ạ. Cả cụm đó là "hiệu năng tính toán".

Các phần khác anh thấy ok rồi.

**Comment by tiepvupsu** [comment]
Anh Gg translate thấy dịch là "Sơ bộ", anh thấy chuẩn hơn.

**Comment by lkhphuc** [comment]
Preliminaries -> Tiền đề thì sao nhỉ?

**Comment by tiepvupsu** [comment]
Anh không có strong preference, vote nhes:

1) Sơ bộ (:+1: )
2) Tiền đề (:heart: )

**Comment by quangnhat185** [comment]
> "Multilayer Perceptrons" -> "Perceptron Đa Tầng"

Từ **layer** có nghĩa là "lớp" dịch "Đa Lớp" đúng hơn chứ nhỉ. Thôi thì học a Tiệp vậy :stuck_out_tongue: : 

**Multilayer**
1. Đa lớp (:+1: )
2. Đa Tầng (:heart:)

**Comment by rootonchair** [comment]
@quangnhat185 bên Yearning dịch là "tầng" đó anh :smile: . Do sợ là trùng với "class" khi nói về label ấy mà.

**Comment by quangnhat185** [comment]
> @quangnhat185 bên Yearning dịch là "tầng" đó anh  . Do sợ là trùng với "class" khi nói về label ấy mà.

Ồ vậy mình dịch "tầng" đi cho cho nó thống nhất.

**Comment by duythanhvn** [comment]
Preliminaries nếu dịch là "Dẫn nhập" thì có ổn hơn không anh em?

**Comment by rootonchair** [comment]
"Dẫn nhập" hình như là "Introduction" rồi

**Comment by rootonchair** [comment]
"Chất Lượng Tính Toán" -> "Hiệu Năng Tính Toán"
như đề xuất ở trên của anh Tiệp

**Comment by quangnhat185** [comment]
Mình close issue này để mở PR
