### ISSUE TITLE
Revise "rmsprop_vn"

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#2070]
Phần này được dịch bởi: **davidnvq**
Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by duythanhvn** [comment]
Những phần này nhờ ông giáo trước cuối tuần nhé, mình có thông tin trên Slack về deadline công bố rồi ấy.

**Comment by quangnhat185** [comment]
Ok ok. Để mình sắp xếp lên trong 2-3 ngày tới
