### ISSUE TITLE
Revise "lr-scheduler_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#2078]
Phần này được dịch bởi:
* **tranyenthy**
* **davidnvq**
* **longnguyen1984**

Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by rootonchair** [comment]
@duythanhvn sao cái này bị block vậy anh?

**Comment by duythanhvn** [comment]
Giai đoạn 1 còn 1 phần chưa dịch đó em.

**Comment by cuongvng** [comment]
em nhận 2 phần này.
