### ISSUE TITLE
Dịch hình chương 12 - Phần 1

### ISSUE THREAD

**Issue by davidnvq** [aivivn/d2l-vn#2172]
Các hình cần dịch:
* [frontends.png](https://github.com/aivivn/d2l-vn/blob/master/img/frontends.png)
* [latencynumbers.png](https://github.com/aivivn/d2l-vn/blob/master/img/latencynumbers.png)
* [mobo-symbol.svg](https://github.com/aivivn/d2l-vn/blob/master/img/mobo-symbol.svg)
* [skylake.svg](https://github.com/aivivn/d2l-vn/blob/master/img/skylake.svg)

###  Các từ cần được dịch trong hình tương ứng:

|Tiếng Anh|Tiếng Việt|
| :---:   | :---:    |
| computing device| thiết bị điện toán |
| kernel | nhân |
|Mutex lock (unlock) | Khóa (mở) Mutex | 
| L1 (L2) cache reference | Tham chiếu bộ nhớ đệm L1 (L2) |
| Main memory reference | Tham chiếu bộ nhớ chính |
| commodity network | mạng thông thường? |
| Disk seek | Tìm kiếm trên ổ nhớ ? |
| Package  | Gói |
| Graphics Cards | Card Đồ họa | 
 

Mọi người thảo luận xem thế nào nhé. Những từ còn lại thấy đã xuất hiện trong glossary nên  k biết có cần thiết cho vào đây k?

**Comment by davidnvq** [comment]
Như hướng dẫn mở new issue mà thấy không cần thiết nhỉ ? @duythanhvn @rootonchair

**Comment by rootonchair** [comment]
Vâng,  vào issue cũ là đủ ạ. Để em update lại hướng dẫn

**Comment by duythanhvn** [comment]
Yep, để em Vinh update lại hướng dẫn, mình move thảo luận qua bên kia rồi. Issue này đóng lại anh em nhé. Ông giáo với phần 2,3 thì cũng comment tương tự thôi hen, không cần tạo issue mới.
