### ISSUE TITLE
Revise "parameterserver_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#2199]
Phần này được dịch bởi:
* **longnguyen1984**
* **rootonchair**
* **trgiang99**

Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by duythanhvn** [comment]
Phần `parameterserver` này còn 2 PR nữa là done, về phần revise thì có 2 phần, phần này xong rồi, nhờ em @minhduc0711 hai phần này nhé?

**Comment by minhduc0711** [comment]
@duythanhvn ok anh, ngày mai hoặc ngày kia em sẽ lên PR ạ
