### ISSUE TITLE
Revise glossary "switch"

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#2270]
Rà soát cách dịch từ `switch` xuyên suốt chương 12 theo #2249 

@duythanhvn em sẽ làm việc này sau khi mọi PR về chương 12 hoàn tất.

**Comment by duythanhvn** [comment]
Sau khi anh tổng rà soát lại toàn bộ chương xong rồi em tiến hành nhé.

**Comment by rootonchair** [comment]
Dạ, khi nào xong thì anh báo để em biết nhé
