### ISSUE TITLE
Dịch "object-detection-dataset_vn" - Phần 2

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#2280]
Phần cần dịch: https://github.com/aivivn/d2l-vn/blame/master/chapter_computer-vision/object-detection-dataset_vn.md#L96-L173

### Hướng dẫn
- [Dịch trực tiếp trên website](https://github.com/aivivn/d2l-vn/blob/master/CONTRIBUTING.md).
- Sau khi nhấn vào phần cần dịch ở trên, hãy chọn **Normal view** và làm theo hướng dẫn ở trên để có thể bắt đầu dịch.

![](https://raw.githubusercontent.com/aivivn/d2l-vn/master/docs/translation-guide/normal-view.png)

**Comment by MarkusKhoa** [comment]
Em cũng nhận phần này @duythanhvn
