### ISSUE TITLE
Revise "fcn_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#2486]
Phần này được dịch bởi: **davidnvq**
Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by lkhphuc** [comment]
oh shit, sorry @duythanhvn giờ mình unassign được không? Quên mất mà sắp tới khá bận.

**Comment by duythanhvn** [comment]
Sure ông giáo ơi, cc @minhduc0711 @cuongvng

**Comment by minhduc0711** [comment]
em nhận phần này ạ

**Comment by lkhphuc** [comment]
thank các giáo.
