### ISSUE TITLE
Dịch "bert-pretraining_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#2564]

**Comment by btcnhung1299** [comment]
Mình xin phép dịch phần này ạ.

**Comment by duythanhvn** [comment]
Hm... anh lại gặp em này..

**Comment by rootonchair** [comment]
@duythanhvn yeah, small world :V

**Comment by duythanhvn** [comment]
Hai đồng chí có quen nhau không :))

**Comment by rootonchair** [comment]
Bọn em là đồng nghiệp ạ :V

**Comment by duythanhvn** [comment]
@btcnhung1299 Nhung cho anh hỏi phần này khi nào có thể lên được em nhỉ?

**Comment by btcnhung1299** [comment]
> @btcnhung1299 Nhung cho anh hỏi phần này khi nào có thể lên được em nhỉ?

Em thống nhất với @rootonchair là trong cuối tuần này sẽ xong ạ.
