### ISSUE TITLE
Move d2l-book in to this repo

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/d2l-vn#263]
Trong bản tiếng Anh, code để tạo các file html, tex và pdf từ file mds được thực hiện thông qua https://github.com/d2l-ai/d2l-book.

Tuy nhiên, vì mình cần phải chỉnh sửa một vài phần cho phù hợp với tiếng Việt nên sẽ cần thay đổi code này rất nhiều. Hiện tại mình đã thay đổi một tí xíu ở https://github.com/aivivn/d2l-book nhưng dự tính trước mắt còn rất rất nhiều việc phải làm để phù hợp với bản tiếng Việt. Vì vậy, việc đưa code d2l-book trực tiếp vào repo này sẽ phù hợp hơn cho việc debug và review.

Mình sẽ phụ trách phần này, sẽ cần thêm trợ giúp từ @rootonchair và @quangnhat185 nữa.

**Comment by tiepvupsu** [comment]
Hiện tại, để tạo các file html và pdf, cần chạy trên cửa sổ dòng lệnh:
```
d2lbook build html/pdf
```
Mình sẽ sửa lại sao cho code có dạng:
```
python our_build.py html/pdf
```

**Comment by quangnhat185** [comment]
![54ss55ix0vwy](https://user-images.githubusercontent.com/41325216/71779518-3c92dd80-2fb7-11ea-88c9-5b25af172d34.jpg)

**Comment by duythanhvn** [comment]
Em thấy folder này về dự án rồi nên em close issue này anh nhé.
