### ISSUE TITLE
Lỗi hiển thị kí tự

### ISSUE THREAD

**Issue by tienhoang1094** [aivivn/d2l-vn#2639]
### Mô tả lỗi
Hiển thị notation

### Ảnh chụp màn hình

![image](https://user-images.githubusercontent.com/58082063/91783765-57435200-ec2b-11ea-97c6-45fd81b8e145.png)

Gửi tại đây: 

### **Desktop (Vui lòng hoàn thiện thông tin như hướng dẫn):**
 - OS: ubuntu18
 - Browser: Chrome

### Đường dẫn đến nội dung có lỗi
- 

### Thông tin thêm
Vui lòng cung cấp thêm bất kỳ thông tin nào bạn tin là hữu ích cho chúng tôi.

**Comment by duythanhvn** [comment]
@tienhoang1094 Hiện tại nhóm đã kiểm tra trang này và đang thấy hiển thị bình thường trên nhiều thiết bị và trình duyệt. Bạn có thể kiểm tra lại giúp nhóm xem trên điện thoại của bạn hoặc trên trình duyệt Chrome chế độ ẩn danh có gặp vấn đề này hay không được chứ?

**Comment by tienhoang1094** [comment]
mọi thiết bị của m với mọi cách đều bị ![Screenshot_20200903-230118_GitHub.jpg](https://user-images.githubusercontent.com/58082063/92139088-74e60680-ee39-11ea-8b65-f37b34433996.jpg)

**Comment by duythanhvn** [comment]
À, bạn giúp mình xem nội dung ở trên website https://d2l.aivivn.com/ nhé, bạn nên xem trên website vì nội dung được trình bày hoàn chỉnh hơn. Bạn xem tại Github thì nội dung này chưa được hỗ trợ LaTeX nên nó không hiển thị đâu bạn nha.

**Comment by tienhoang1094** [comment]
![image](https://user-images.githubusercontent.com/58082063/92889451-71a5d880-f440-11ea-9f54-a4eb9ad0aa91.png)
lỗi nữa b

**Comment by duythanhvn** [comment]
Cảm ơn @tienhoang1094, nhóm sẽ cập nhật trong thời gian tới.
