### ISSUE TITLE
Dịch nội dung hình ảnh statistical_significance.svg

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#265]
Mình có một hình ảnh nằm trong phần `statistics_vn.md` cần dịch: https://github.com/aivivn/d2l-vn/blob/master/img/statistical_significance.svg

Hình ảnh mình sẽ dựng lại để có chất lượng tốt hơn. Một bạn giúp mình dịch phần nội dung của hình ảnh, Issue này cũng sẽ dùng để phản biện về phần dịch đó.

Tham khảo hướng dẫn đóng góp dịch hình ảnh: https://github.com/aivivn/d2l-vn/blob/master/img/README.md

**Comment by rootonchair** [comment]
Các từ có trong ảnh
![image](https://user-images.githubusercontent.com/23548268/72885632-e05fe580-3d3a-11ea-890f-2e73b43c63c5.png)

| Tiếng Anh | Tiếng Việt |
| --- | --- |
| 95% Confidence interval | Khoảng tin cậy 95% |
| Very unusual observations | Các quan sát rất hiếm gặp |
| 97.5% significance threshold | Ngưỡng ý nghĩa 97,5% |
| An outlier | Một điểm ngoại lai |
| Value of observation | Giá trị quan sát |
| Probability of observation | Xác suất của các quan sát |
