### ISSUE TITLE
Revise "bert-pretraining_vn"

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#2712]
Phần này được dịch bởi: **btcnhung1299**
Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by duythanhvn** [comment]
@minhduc0711 được thì em revise kỹ phần này giúp anh nhé.

**Comment by minhduc0711** [comment]
@duythanhvn ok ạ 👍
