### ISSUE TITLE
Dịch "deepfm_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#2721]
Phần cần dịch: https://github.com/aivivn/d2l-vn/blame/master/chapter_recommender-systems/deepfm_vn.md#L1-L81

### Hướng dẫn
- [Dịch trực tiếp trên website](https://github.com/aivivn/d2l-vn/blob/master/CONTRIBUTING.md).
- Sau khi nhấn vào phần cần dịch ở trên, hãy chọn **Normal view** và làm theo hướng dẫn ở trên để có thể bắt đầu dịch.

![](https://raw.githubusercontent.com/aivivn/d2l-vn/master/docs/translation-guide/normal-view.png)

**Comment by trGiang99** [comment]
@duythanhvn Assign giúp em phần này với ạ.

**Comment by duythanhvn** [comment]
@trGiang99 em nghĩ sao về diễn viên Anh Đức?

à, nhầm. em có cảm xúc gì khi là người solo chương RS? liệu, em có muốn tiếp tục solo từ sau chương 16 đến hết chương 19 không? anh sẽ hú toàn bộ 500 anh em ra review .....

**Comment by trGiang99** [comment]
Đúng hướng nghiên cứu anh 😅
Với lại chương này cũng ngắn hơn so với các chương trước nhiều mà 😆😆
