### ISSUE TITLE
Revise "natural-language-inference-attention_vn" - Phần 2

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#2785]
Phần này được dịch bởi: **markuskhoa**
Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by quangnhat185** [comment]
@duythanhvn ông giáo ơi phần này có 5 phần dịch thì chỉ mới dịch 3 phần thôi #2665

**Comment by duythanhvn** [comment]
@quangnhat185 Cảm ơn ông giáo, cái này mình mở thiếu rồi. Để mình bổ sung.

**Comment by duythanhvn** [comment]
@quangnhat185 Ông giáo tạo branch mới từ master để revise nhé, phần dịch đã được bổ sung. Cảm ơn ông giáo nhiều.
