### ISSUE TITLE
Dịch "index_vn" & "d2l_vn"

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#2959]
Phần cần dịch: https://github.com/aivivn/d2l-vn/blob/master/chapter_appendix-tools-for-deep-learning/index_vn.md

### Hướng dẫn
- [Dịch trực tiếp trên website](https://github.com/aivivn/d2l-vn/blob/master/CONTRIBUTING.md).
- Sau khi nhấn vào phần cần dịch ở trên, hãy chọn **Normal view** và làm theo hướng dẫn ở trên để có thể bắt đầu dịch.

![](https://raw.githubusercontent.com/aivivn/d2l-vn/master/docs/translation-guide/normal-view.png)

**Comment by rootonchair** [comment]
Em xin nhận phần này và 3 phần kế tiếp
