### ISSUE TITLE
Revise "maximum-likelihood_vn"

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#3038]
Phần này được dịch bởi:
* **tranyenthy**
* **markuskhoa**

Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by LongNguyen1984** [comment]
Mình nhận phần này nhé

**Comment by duythanhvn** [comment]
@LongNguyen1984 Em để đường dẫn trong phase 1 chỉ để cho những bạn mới vào chưa quen thì có thêm link dễ xác định đoạn khi bắt đầu hơn thôi anh ạ, phase 2 này thì em không để vì anh em quen việc hết rồi ạ.

Còn hướng dẫn chi tiết thì em đã viết hết trong tập tin **[CONTRIBUTING.md](https://github.com/aivivn/d2l-vn/blob/master/CONTRIBUTING.md)** của dự án, theo đó cụ thể thì anh nhấn vào tập tin **[maximum-likelihood_vn.md](https://github.com/aivivn/d2l-vn/blob/master/chapter_appendix-mathematics-for-deep-learning/maximum-likelihood_vn.md)**, anh nhấn vào hình cây bút để **Edit this file**.

![](https://github.com/aivivn/d2l-vn/raw/master/docs/translation-guide/web-step-02.png)

Phần này của anh là cả một tập tin đấy luôn nên anh đọc hết giúp em luôn nha anh, chứ không có cắt phần gì đâu ạ.

Những phần revise khác nếu anh có nhận thì cũng tương tự ạ.
