### ISSUE TITLE
Revise "naive-bayes_vn"

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#3041]
Phần này được dịch bởi:
* **tranyenthy**
* **longnguyen1984**

Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by trGiang99** [comment]
@duythanhvn Assign giúp em phần này với ạ. Em thử revise một phần nhé :D

**Comment by duythanhvn** [comment]
@trGiang99 vậy là em chưa xem Slack đúng hông..

**Comment by trGiang99** [comment]
Em xem slack rồi em mới dám vào nhận revise chứ anh :D
