### ISSUE TITLE
Revise "jupyter_vn"

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#3051]
Phần này được dịch bởi: **rootonchair**
Nếu bạn đã dịch phần này, vui lòng bỏ qua việc revise.

**Comment by duythanhvn** [comment]
@davidnvq lên sớm ông giáo nhé.

**Comment by davidnvq** [comment]
@duythanhvn mai len ok k sep?

**Comment by duythanhvn** [comment]
@davidnvq yeah, mai hay mốt cũng được, mình remind thôi 😄
