### ISSUE TITLE
Revise chương Introduction - Phần 1.3.2. Học không giám sát

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#313]
Chúng mình đã phân vùng nội dung cần revise, bạn tìm đến phân vùng được đánh dấu với cú pháp:

`<!-- Revise lần 2 - mục x.x.x - Bắt đầu -->` 
`<!-- Revise lần 2 - mục x.x.x - Kết thúc -->`

với x.x.x là số phần được ghi rõ trên tiêu đề. 

Thứ tự thực hiện: #283

**Comment by rootonchair** [comment]
Em sẽ nhận phần này
