### ISSUE TITLE
Sai đường dẫn đến bản dịch tiếng Việt

### ISSUE THREAD

**Issue by trgiangdo** [aivivn/d2l-vn#3133]
Đường dẫn trên trang chủ Tiếng Anh, và trong Readme là https://d2l.aivivn.com/.
Đường dẫn đúng nên là https://vi.d2l.ai/

**Comment by thanhcsf** [comment]
Hi em,

Nó không sai đâu em nha, hiện tại chưa điều hướng là vì đường dẫn dưới chưa được công khai là bản chính nha em.
Còn với đường dẫn trên anh sẽ kiểm tra lại.

Cảm ơn em nha.

**Comment by thanhcsf** [comment]
Đã fix rồi em nha.
