### ISSUE TITLE
chapter_introduction/index_vn - Lỗi 1. Ảnh ko co giãn - 2. Dịch sót - 3+4. Văn phong.

### ISSUE THREAD

**Issue by maisonhai3** [aivivn/d2l-vn#320]
Mình nêu lại những lỗi nhỏ đã chỉ ra ở [comment bên slack](https://d2l-vn.slack.com/archives/CQDJUKZ0A/p1578497892018400?thread_ts=1578497892.018400)

Lỗi này nằm ở [bản web](https://d2l.aivivn.com/chapter_introduction/index_vn.html#)

Đây là issue đầu tiên mình tạo, có gì chưa ngon anh em góp ý giúp.

* [x] Lỗi 1. Ảnh hai con mèo ngay sau Fig. 1.1.2 : quá to & không thể co giãn theo kích thước cửa sổ.
* [x] Lỗi 2. Chưa dịch: Fig. 1.3.2 dịch chú thích ảnh phía trên¶          
* [ ] Lỗi 3. Chưa viết hoa tên riêng: linux > nên > Linux.
* [x] Lỗi 4. kẻ trộm, và những người bạn. Lỗi chưa đổi văn phong tiếng Anh sang văn phong Việt Nam > nên > kẻ trộm và những người bạn.

**Comment by tiepvupsu** [comment]
@maisonhai3 Lỗi ảnh còn mèo là như thế nào nhỉ? Mình xem thì thấy ok ngoại trừ việc con mèo đầu tiên hơi cao hơn một chút.

**Comment by maisonhai3** [comment]
@tiepvupsu :
- Khi không mở window maximize, thì 2 con mèo bị như này anh (*ảnh đính kèm*).
![Screenshot from 2020-01-11 08-55-01](https://user-images.githubusercontent.com/28621061/72197112-3b96fb80-3450-11ea-97a7-bf8819af1297.png).

- Update thêm: sáng nay mình mở lại link đó: không còn thấy cái **Mục lục** - Navigator bên tay trái như bản tiếng Anh nữa. (*hình bản tiếng Anh*).
![Screenshot from 2020-01-11 08-48-06](https://user-images.githubusercontent.com/28621061/72197129-6da85d80-3450-11ea-8b6b-3795ad329f8a.png)

Chỉ còn thấy như này. (*hình Việt - maximize*)
![Screenshot from 2020-01-11 08-58-21](https://user-images.githubusercontent.com/28621061/72197135-87e23b80-3450-11ea-809c-fd3bedb9cc3e.png)

Không hiểu đây là lỗi hay tính năng??

**Comment by tiepvupsu** [comment]
Em thử trình duyệt khác xem thế nào. Trên máy anh không thấy hiện tượng này nữa.

**Comment by maisonhai3** [comment]
@tiepvupsu : giết em đi.

Giờ mở bằng cả chrome, firefox, brave đều ko hiện gì. Trắng xóa.

![Screenshot from 2020-01-11 15-26-30](https://user-images.githubusercontent.com/28621061/72201456-c561bb80-3486-11ea-821a-f2899cc02128.png)

(Lúc 15:27 - đã restart máy - 3 trình duyệt đều update mới nhất - Chạy Linux - Pop OS 19.10)

**Comment by duythanhvn** [comment]
@maisonhai3 Bình tĩnh bình tĩnh 😅Mình cũng kiểm tra và thấy đúng là có vấn đề này. Website hiện tại chỉ hiện nội dung (không có định dạng cấu trúc). Mình nghĩ đây là lỗi trong quá trình deloy, ghi nhận nghen. 😅

**Comment by tiepvupsu** [comment]
Hóa ra anh mới là thằng phải restart rồi thử nhiều trình duyệt. Máy anh trình duyệt nào cũng ổn :(

**Comment by maisonhai3** [comment]
Mình mở lại bằng windows 10, cả chrome với firefox cũng vẫn lỗi.

Sao máy anh @tiepvupsu config như nào mà thần thánh thế ko biết.

![image](https://user-images.githubusercontent.com/28621061/72665889-603a3700-3a3f-11ea-8daa-a3096259af48.png)

**Comment by tiepvupsu** [comment]
Ảo nhỉ, máy anh cũng bị thế rồi. Để anh kiểm tra lại.

Anh em cứ lo revise nốt preface trước Tết. Anh sẽ cố gắng công bố đúng mùng 1 Tết.

**Comment by tiepvupsu** [comment]
Xong hết rồi nhé.

**Comment by maisonhai3** [comment]
Cảm ơn các anh đã sửa lỗi nhé.
