### ISSUE TITLE
Thêm link thảo luận tới ForumMLCB

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/d2l-vn#373]
Mặc định thêm link Thảo luận tiếng Việt đến 
https://forum.machinelearningcoban.com/c/d2l
trong mọi trang.

**Comment by duythanhvn** [comment]
Vậy em loại bỏ các QR liên kết ở mục thảo luận anh hen.

**Comment by tiepvupsu** [comment]
Ok em.
