### ISSUE TITLE
Dịch chapter_preliminaries/index_vn  - Phần 01

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#381]

**Comment by maisonhai3** [comment]
Mình sẽ dịch phần này nhé.

Sẽ xong trước chủ nhật.

**Comment by duythanhvn** [comment]
@maisonhai3 bạn xem giúp mình các phần còn để label `help wanted` và comment ở đó giúp mình nhé, phần này mình đã nhận rồi.

**Comment by maisonhai3** [comment]
À, ok.

**Comment by tiepvupsu** [comment]
Đừng quên phần này nhé @duythanhvn.
