### ISSUE TITLE
Dịch "chapter_appendix_math/single-variable-calculus_vn" - Phần 12 (Phần cuối)

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#406]

**Comment by tamnguyenvan** [comment]
Em xin đóng góp phần này ạ. @duythanhvn

**Comment by duythanhvn** [comment]
@tamnguyenvan Cảm ơn bạn đã tham gia. Không biết bạn đã tham gia vào Slack của nhóm dịch chưa nhỉ?

**Comment by tamnguyenvan** [comment]
Em chưa ạ.

**Comment by duythanhvn** [comment]
Vậy bạn tranh thủ tham gia **[tại đây](https://docs.google.com/forms/d/e/1FAIpQLScYforPRBn0oDhqSV_zTpzkxCAf0F7Cke13QS2tqXrJ8LxisQ/viewform)** nhé, ở Slack bạn có thể trao đổi nhanh, gợi ý hỗ trợ bạn các vấn đề bạn chưa rõ và tham gia thảo luận các vấn đề nhỏ nhỏ của dự án.
