### ISSUE TITLE
Các phương trình không được xử lý từ 1.3.1.2 trong chương "Giới thiệu"

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#431]
Em có check bản deploy trên trang web thì thấy từ phần 1.3.1.2 trở đi, các phương trình (những phần trong `$...$`) không được xử lý nữa. Em kiểm tra file markdown thì mọi thứ vẫn bình thường

![image](https://user-images.githubusercontent.com/23548268/73538284-36303e00-445d-11ea-9a23-0753459f6bf4.png)

**Comment by duythanhvn** [comment]
Tình hình là anh đang thấy nó hiển thị bình thường đó em ơi. Em đã thử xoá cache, xem ẩn danh hoặc trên thiết bị khác chưa?
<img width="1095" alt="Screen Shot 2020-01-31 at 22 13 21" src="https://user-images.githubusercontent.com/8481767/73550309-f413f600-4476-11ea-9bc4-daceff460261.png">

**Comment by rootonchair** [comment]
Cảm ơn anh. Em xem ở chế độ ẩn danh thì bình thường lại rồi
