### ISSUE TITLE
Dịch tiêu đề sách "Dive into Deep Learning"

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/d2l-vn#45]
Đề xuất:

* Đắm mình vào Học Sâu
* Nhảy ùm vào Học Sâu (@ncthuong đề xuất)

**Comment by SumoBBQ** [comment]
* Hòa mình, chìm đắm, đắm chìm vào Học sâu

**Comment by goldenretriever2015** [comment]
Khi mình tham dịch sách, mình thấy tiếng Việt thật phong phú. Mình thấy các cách dịch gợi ý trên đều hợp ý, tuy nhiên mình vote cho cách dịch "Đắm mình vào học sâu". Ngoài ra mình cũng góp 1 cách dịch khác là "Học sâu về học sâu" hoặc "Chuyên sâu về học sâu".

**Comment by thhung** [comment]
Em vote cho "Đắm mình vào Học sâu". Thỉnh thoảng cũng cần mềm mại một tý.

**Comment by lkhphuc** [comment]
Vote "Đắm mình vào Học sâu".

**Comment by quan-nguyen-7121996** [comment]
E đề xuất ba tên sau:
Khám phá học sâu
Lặn trong học sâu
Dấn thân vào học sâu

**Comment by kenbi93** [comment]
Theo em thì:
Vùng vẫy trong học sâu
