### ISSUE TITLE
Dịch "lookup-api_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#522]
Phần cần dịch: https://github.com/aivivn/d2l-vn/blame/master/chapter_preliminaries/lookup-api_vn.md#L1-L72

**Comment by trhgquan** [comment]
Dear anh, cho em xin dịch phần này ạ

**Comment by duythanhvn** [comment]
@trhgquan Cảm ơn bạn đã tham gia. Không biết bạn đã đăng ký vào Slack nhóm dịch thuật chưa nhỉ?

**Comment by trhgquan** [comment]
Dear anh @duythanhvn , em vừa điền đơn xong ạ
