### ISSUE TITLE
Dịch "lookup-api_vn" - Phần 2

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#523]
Phần cần dịch: https://github.com/aivivn/d2l-vn/blame/master/chapter_preliminaries/lookup-api_vn.md#L74-L120

**Comment by hagiangnguyen-1996** [comment]
Em xin phép nhận phần này ạ

**Comment by duythanhvn** [comment]
@hagiangnguyen-1996 Phần này không biết khi nào bạn đưa lên được nhỉ?

**Comment by hagiangnguyen-1996** [comment]
@duythanhvn Hi anh, em xin lỗi vì có chút chậm trễ. Em xin phép gửi lại vào 9PM 12/2 (hôm nay ạ). Em cảm ơn.

**Comment by duythanhvn** [comment]
@hagiangnguyen-1996 Em ơi, phần này lên được trong cuối tuần này không em ha?

**Comment by duythanhvn** [comment]
@hagiangnguyen-1996 Hi em, anh thấy em nhận phần này đã lâu rồi nhưng chưa có động tĩnh gì. Vì thế, anh tạm assign phần này cho người khác nhằm đảm bảo tiến độ của dự án. 

Những phần mới nhóm vẫn luôn mở với label `status: help wanted` trong phần Issues của dự án. Vì vậy, khi em có thời gian hơn thì có thể nhận và hỗ trợ thêm dự án nhé.

Cảm ơn em.

**Comment by tiepvupsu** [comment]
Anh đang rảnh, để anh dịch phần này nhé.
