### ISSUE TITLE
Dịch ảnh "computegraph.svg"

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#530]
[Hướng dẫn dịch các từ trong hình](https://github.com/aivivn/d2l-vn/blob/master/img/README.md).

**Comment by tamnguyenvan** [comment]
Từ này không biết có cần dịch không ạ. Nó là tên toán tử bằng Tiếng Anh.
| Tiếng Anh | Tiếng Việt|
|:---|:---|
|add|cộng|

**Comment by tiepvupsu** [comment]
@tamnguyenvan em đang nói đến hình 12.1.1 đúng không? https://d2l.ai/chapter_computational-performance/hybridize.html

Vì hình này liên quan đến đoạn code ngay phía trên nên mình nên để nó thống nhất với code. Trong code để là `add` nên mình giữ nguyên.

**Comment by tamnguyenvan** [comment]
@tiepvupsu chuẩn hình đó ạ.

**Comment by tiepvupsu** [comment]
Ok, vậy anh sẽ đóng issue này.
