### ISSUE TITLE
Dịch ảnh "singleneuron.svg"

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#604]
File ảnh: [singleneuron.svg](https://github.com/aivivn/d2l-vn/blob/master/img/singleneuron.svg)

![image](https://user-images.githubusercontent.com/23548268/74125897-16d9a380-4c09-11ea-956c-0f31a882d2ad.png)

Hướng dẫn dịch ảnh [img/README.md](https://github.com/aivivn/d2l-vn/blob/master/img/README.md)

**Comment by tamnguyenvan** [comment]
|Tiếng Anh|Tiếng Việt|
|---|---|
|Input layer|Tầng đầu vào|
|Output layer|Tầng đầu ra|

**Comment by duythanhvn** [comment]
@tamnguyenvan Phần này bạn có nhận thực hiện được bước 3 như trong hướng dẫn không nhỉ?

**Comment by tamnguyenvan** [comment]
@duythanhvn Chắc không ạ. Em không rành chỉnh sửa ảnh lắm.

**Comment by rootonchair** [comment]
Vậy mình sẽ làm phần chỉnh sửa ảnh. Cảm ơn bạn
