### ISSUE TITLE
Dịch ảnh "Neuron.svg"

### ISSUE THREAD

**Issue by rootonchair** [aivivn/d2l-vn#605]
File ảnh: [Neuron.svg](https://github.com/aivivn/d2l-vn/blob/master/img/Neuron.svg)

![image](https://user-images.githubusercontent.com/23548268/74126302-2b6a6b80-4c0a-11ea-8d0c-4bfc8387fedb.png)

Hướng dẫn dịch ảnh [img/README.md](https://github.com/aivivn/d2l-vn/blob/master/img/README.md)

**Comment by hainguyen15** [comment]
|Tiếng Anh|Tiếng Việt|
| :---:   | :---:    |
| Dendrite| Sợi nhánh|
| Nucleus| Nhân tế bào|
| Cell body| Thân tế bào|
| Axon| Sợi trục|
| Myelin sheath| Bao miêlin|
| Schwann cell| Tế bào Schwann|
| Node of Ranvier| Eo Ranvier|
| Axon Terminal| Đầu cuối sợi trục|

Ảnh dịch (github không hỗ trợ attach svg nên mình nén lại thành file zip): 
[Neuron_dich.zip](https://github.com/aivivn/d2l-vn/files/4184032/Neuron_dich.zip)

**Comment by duythanhvn** [comment]
@hainguyen15 Cảm ơn bạn đã thực hiện task này. Lưu ý với bạn, ở bước hai này mình chỉ mới thảo luận về cách dịch các từ, cụm từ trên hình trong Issue này thôi. Ở bước tiếp theo trong hướng dẫn, bạn mới thay đổi nội dung trong hình và đẩy trực tiếp hình đó vào dự án thông qua một PR mới.

**Comment by hainguyen15** [comment]
Vâng cảm ơn anh đã nhắc nhở ạ

**Comment by rootonchair** [comment]
@hainguyen15 mình đã check qua, các từ của bạn đều đúng. Mình cũng đã check file svg của bạn. Bạn vui lòng lập PR để thêm hình đã dịch vào folder `img` nhé. 

Cảm ơn bạn đã tham gia.

**Comment by hainguyen15** [comment]
> @hainguyen15 mình đã check qua, các từ của bạn đều đúng. Mình cũng đã check file svg của bạn. Bạn vui lòng lập PR để thêm hình đã dịch vào folder `img` nhé.
> 
> Cảm ơn bạn đã tham gia.

dạ cho em hỏi mình đặt tên file y như file cũ để ghi đè lên hay đặt khác vậy ạ ?

**Comment by duythanhvn** [comment]
@hainguyen15 Em thay thế hình cũ bằng hình mới giúp anh nhé.

**Comment by hungthuanmk** [comment]
@hainguyen15 Bạn ơi synapses mình nên dịch như thế nào đây? Mình định dịch là _Khớp thần kinh_

**Comment by rootonchair** [comment]
@hungthuanmk mình thấy bạn có thể giữ nguyên từ này. Mình search khớp thần kinh thì không có nhiều kết quả liên quan cho lắm
