### ISSUE TITLE
Thêm pull request templates cho revise và dịch hình 

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/d2l-vn#639]
@duythanhvn và @rootonchair tìm hiểu thêm xem nếu có nhiều pull request templates thì lúc tạo PR chọn như thế nào nhé.

Nếu hợp lý thì mình tạo riêng PR template cho các phần còn lại ngoài phần dịch lần đầu. Các PR khác thì cần dạng `close #` cho nhanh.

**Comment by rootonchair** [comment]
Nếu chọn PR template trong nhiều cái thì mình dùng thêm query `?template=<tên-template>.md` cho Pull Request URL. Theo như trong [đây](https://github.community/t5/How-to-use-Git-and-GitHub/Multiple-Pull-Request-Templates/td-p/20909) thì hiện tại thì github chưa hỗ trợ UI cho việc chọn template của PR nên nếu có nhiều hơn một template thì mình phải chọn bằng cách như trên. Em đang nghĩ xem có cách nào để đơn giản hóa hơn không.

Tham khảo: https://blog.axosoft.com/enhancing-pull-request-descriptions-templates/

**Comment by tiepvupsu** [comment]
Anh nghĩ không cần mất thời gian vào phần này nữa. Lưu ý với các bạn là template chỉ áp dụng cho các PR dịch lần đầu.

Mình có thể thêm note đó vào ngay trong template.

**Comment by duythanhvn** [comment]
Em cũng tìm hiểu được những thông tin như em Vinh có đề cập, tính năng này được Github hỗ trợ trên bản Enterprise có UI đầy đủ như bên Gitlab, tiện thể em cũng gửi request cho Github, hy vọng họ quan tâm mà update. Khi nào có thì mình dùng vậy.

Hai template này thì em cũng thấy cứ để vậy thôi, template này dùng Revise em quan sát phần lớn anh em đã quen việc thì cũng chỉ dùng mỗi `Close #link_issue`.  Có để nguyên mà điền như template hiện tại cũng không sao. Hình ảnh thì nay mới thấy thêm em Hải có thể sửa hình (đội mới có 3 người), có thể nhắn riêng được.

Vậy, tạm close Issue này lại. Việc có thêm template cho PR khá hay nên em tạm noted. Khi nào có hỗ trợ thì mình dùng (có khi qua dự án khác rồi cũng nên).

Thế nhé anh em.
