### ISSUE TITLE
Dịch chữ trong các hình vẽ của chapter_introduction/index_vn.md

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/d2l-vn#66]
https://github.com/aivivn/d2l-vn/blob/master/chapter_introduction/index_vn.md

**Comment by rootonchair** [comment]
Ở dưới là bảng các từ có trong ảnh của phần Introduction. Mọi người review nhé. (github không hỗ trợ svg nên mình không tải ảnh lên được)

|Tiếng Anh| Tiếng Việt | Từ ảnh |
| :---: | :---: | :---: |
| Wake word model | Mô hình phát hiện cụm kích hoạt |`wake-word.svg`|
| Design a model | Thiết kế một mô hình | `fig_ml_loop.svg` |
| Grab new data | Lấy dữ liệu mới | `fig_ml_loop.svg` |
| Update the model | Cập nhật mô hình | `fig_ml_loop.svg` |
| Check if good enough | Kiểm tra liệu đã đủ tốt | `fig_ml_loop.svg` |
| Training inputs | Đầu vào huấn luyện | `fig_supervised_learning.svg` & `fig_data_collection.svg` |
| Supervised learning | Học có giám sát | `fig_supervised_learning.svg` & `fig_data_collection.svg` |
| Training labels | Nhãn huấn luyện | `fig_supervised_learning.svg` & `fig_data_collection.svg` |
| Input | Đầu vào | `fig_supervised_learning.svg` & `fig_data_collection.svg` |
| Model| Mô hình | `fig_supervised_learning.svg` & `fig_data_collection.svg` | 
| Output | Đầu ra | `fig_supervised_learning.svg` & `fig_data_collection.svg` |
| Environment | Môi trường | `fig_data_collection.svg` & `rl_environment.svg` |
| Agent | (chưa có ý tưởng) | `rl_environment.svg` |
| Action | Hành động | `rl_environment.svg` |
| Reward | Phần thưởng | `rl_environment.svg` |
| Observation | Quan sát | `rl_environment.svg` |

Từ `Agent` là một thuật ngữ trong RL nên mình chưa dịch vội. Mọi người có ý tưởng nào để dịch từ này có thể đóng góp

**Comment by lkhphuc** [comment]
@rootonchair Agent có thể dịch là "tác nhân" được không?

**Comment by rootonchair** [comment]
@lkhphuc Trong RL, "Agent" kiểu giống như một thực thể tương tác với môi trường. Nếu dịch là "tác nhân" sẽ không mang đủ nghĩa.

**Comment by lkhphuc** [comment]
Mình thấy chẳng qua tác nhân thường được dùng trong ngữ cảnh khác như hoá học, vật lý nên mình mới thấy nó kì kì thôi.
Chứ thực ra "tác nhân" thực ra mang chính xác ý nghĩa đó đó mà. Tác nhân: Ngừoi tương tác.

**Comment by rootonchair** [comment]
@lkhphuc bạn nói đúng. Mình đã search qua trên mạng. Trong sinh học thì "agent" cũng được dịch là tác nhân. Mình sẽ edit lại comment trên.

**Comment by tiepvupsu** [comment]
👍 

@rootonchair chỗ "grab new data" em đổi thành "thu thập dữ liệu mới". Từ "thu thập" được hiểu là mình đi tìm kiếm thêm, còn từ "lấy" không rõ là lấy từ đâu.

@lkhphuc Em thêm từ "agent" và glossary nhé.

**Comment by rootonchair** [comment]
@tiepvupsu  Em có đọc thì hình ảnh được dùng chung với đoạn dưới đây nên em nghĩ "Lấy" là từ phù hợp hơn khi dùng trong quá trình training
> As shown in :numref:`fig_ml_loop`, the training process usually looks like this:
> 
> 1. Start off with a randomly initialized model that cannot do anything useful.
> 1. Grab some of your labeled data (e.g., audio snippets and corresponding ``{yes, no}`` labels)
> 1. Tweak the knobs so the model sucks less with respect to those examples
> 1. Repeat until the model is awesome.

**Comment by tiepvupsu** [comment]
ok, vậy thì đúng là "lấy" rồi.

**Comment by rootonchair** [comment]
Vậy mai em sẽ tiến hành dịch.
