### ISSUE TITLE
Chuyển template "Những người thực hiện" về heading 2 (thay vì 3)

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/d2l-vn#676]
Hiện đang là:
```
### Những người thực hiện
```
kết quả hiện thị:
![image](https://user-images.githubusercontent.com/2201237/74719444-e38aac00-51e8-11ea-9a16-6391fbab7b7b.png)

Đúng ra nên là 
```
## Những người thực hiện
```
để "Những người thực hiện" và "Thảo luận" ngang hàng với nhau.

Mình đã sửa lỗi này ở chương trước nhưng không hiểu vì sao giờ vẫn bị.

**Comment by duythanhvn** [comment]
Này do em không để ý khi sửa bản `conntributors_template_vn.md` lúc tạo bản dịch thô mới, nên cái này em kiểm tra và cập nhật lại trong một PR là xong ạ. Cảm ơn anh.
