### ISSUE TITLE
Tổng hợp lỗi hiển thị chương Preliminaries

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#704]
Anh em khi xem chương Preliminaries (Sơ bộ) ở bản deloy trên trang https://d2l.aivivn.com/ nếu thấy lỗi chính tả, lỗi formatting,.... thì phản hồi ở đây (kèm theo hình ảnh & đường dẫn) giúp mình nhé.

**Comment by tiepvupsu** [comment]
![image](https://user-images.githubusercontent.com/2201237/75086624-3e731a80-54eb-11ea-9f93-8f4098b1c2e8.png)

Không có hình.

Hình này có lẽ được tạo bằng cách chạy notebook. Anh sẽ phải tìm hiểu.

**Comment by rootonchair** [comment]
Em nghĩ cái này chắc nên để nguyên thôi anh. Vì nó từ code mà ra và mình không sửa code.

**Comment by rootonchair** [comment]
![image](https://user-images.githubusercontent.com/23548268/75086919-77070880-556c-11ea-86cd-9858bbe756d5.png)
![image](https://user-images.githubusercontent.com/23548268/75086936-ad448800-556c-11ea-9081-2aa604694678.png)

Phương trình bị mất label, đồng thời cũng ảnh hưởng đến mấy cái ref ở dưới.
Link: https://d2l.aivivn.com/chapter_preliminaries/linear-algebra_vn.html#ma-tran

**Comment by tiepvupsu** [comment]
> Em nghĩ cái này chắc nên để nguyên thôi anh. Vì nó từ code mà ra và mình không sửa code.

À, mỗi file mình dịch là một notebook. Để có hình thì mình phải `eval` cái notebook ấy. Anh đang cài đặt.

**Comment by tiepvupsu** [comment]
@rootonchair về cái label cho phương trình, em check nhanh xem chỗ đó có vấn đề gì không. Vì các phương trình khác trong file vẫn có nên anh nghĩ lỗi dễ sửa.

**Comment by tiepvupsu** [comment]
![image](https://user-images.githubusercontent.com/2201237/75087151-a298dd00-54f1-11ea-8314-9db3ce952285.png)

**Comment by rootonchair** [comment]
> @rootonchair về cái label cho phương trình, em check nhanh xem chỗ đó có vấn đề gì không. Vì các phương trình khác trong file vẫn có nên anh nghĩ lỗi dễ sửa.

Ngon nghẻ rồi nhé anh Tiệp, không biết là do anh gen lại hay sao mà mấy cái phương trình bình thường lại rồi
