### ISSUE TITLE
Dịch "fashion-mnist_vn" - Phần 1

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#756]

**Comment by quangnhat185** [comment]
Mình nhận từ phần 1-4, thứ 7 CN sẽ lên đủ nhé

**Comment by duythanhvn** [comment]
.... Ông giáo bình tĩnh thôi nào....

**Comment by quangnhat185** [comment]
![3q1yl7](https://user-images.githubusercontent.com/41325216/75115955-f3c8de00-5663-11ea-9d59-18f5f98de55e.jpg)

**Comment by tamnguyenvan** [comment]
@quangnhat185 Nhìn phần assignee hoảng quá :))))
