### ISSUE TITLE
Dịch "mlp-gluon_vn"

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#839]
Phần cần dịch: https://github.com/aivivn/d2l-vn/blob/master/chapter_multilayer-perceptrons/mlp-gluon_vn.md

### Hướng dẫn
- [Dịch trực tiếp trên website](https://github.com/aivivn/d2l-vn/blob/master/CONTRIBUTING.md).
- Sau khi nhấn vào phần cần dịch ở trên, hãy chọn **Normal view** và làm theo hướng dẫn ở trên để có thể bắt đầu dịch.

![](https://raw.githubusercontent.com/aivivn/d2l-vn/master/translation_team/normal-view.png)

**Comment by duythanhvn** [comment]
@tranyenthy Phần này trước nhé :)

**Comment by duythanhvn** [comment]
@tranyenthy Bạn nhận được tin nhắn của mình hông nhỉ?

**Comment by duythanhvn** [comment]
Anh giao em phần này nhé @lyphilong

**Comment by lyphilong** [comment]
@duythanhvn okay anh có gì cuối tuần này em lên hết luôn cả hai luôn.

**Comment by tranyenthy** [comment]
> 
> 
> @tranyenthy Bạn nhận được tin nhắn của mình hông nhỉ? Mình sẽ giao bạn phần này trước nhé, bạn comment giúp mình hen.
> 
> Mình sẽ assign tối đa 2 task, khi mình thấy PR được đẩy lên (ít nhất là 1 PR khi nhận 2 task) thì mình sẽ tiếp tục assign, tránh việc ôm task.

Xin lỗi bạn, ko hiểu tại sao bên mình ko hiện noti gì cả. :( @duythanhvn
