### ISSUE TITLE
Tổng hợp lỗi hiển thị chương Linear Networks

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#954]
Anh em khi xem chương Linear Networks ở bản deloy trên trang https://d2l.aivivn.com/ nếu thấy lỗi chính tả, lỗi formatting,.... thì phản hồi ở đây (kèm theo hình ảnh & đường dẫn đến nội dung) giúp mình nhé.

**Comment by minhduc0711** [comment]
Lỗi công thức toán ở https://d2l.aivivn.com/chapter_linear-networks/linear-regression_vn.html#mo-hinh-tuyen-tinh

![Screenshot from 2020-03-10 22-03-07](https://user-images.githubusercontent.com/34294427/76332940-8683a100-6323-11ea-9734-2a90421abba1.png)

**Comment by lkhphuc** [comment]
![Screenshot 2020-03-12 at 15 37 11](https://user-images.githubusercontent.com/12573521/76538521-59480780-6477-11ea-8f5a-6fb7e34c6336.png)
3.1.1.2. Phân phối Chuẩn và Hàm mất mát Bình phương còn chữ `where` trong công thức.

**Comment by duythanhvn** [comment]
@minhduc0711 Lỗi này thiếu một ngoặc `}`. Fixed.
@lkhphuc Fixed.

**Comment by tiepvupsu** [comment]
![image](https://user-images.githubusercontent.com/2201237/77029937-5f982100-695a-11ea-8a68-a70b7e751666.png)
InIn nghiêng

**Comment by tiepvupsu** [comment]
![image](https://user-images.githubusercontent.com/2201237/77029956-7179c400-695a-11ea-8d5c-64b1ddf413d4.png)
Đổi luôn `price`.

**Comment by tiepvupsu** [comment]
![image](https://user-images.githubusercontent.com/2201237/77030027-a2f28f80-695a-11ea-974a-fac8586e481f.png)
where

**Comment by tiepvupsu** [comment]
![image](https://user-images.githubusercontent.com/2201237/77030044-ac7bf780-695a-11ea-8009-1ebb4e53645f.png)
`where`

**Comment by duythanhvn** [comment]
Link anh ơi

**Comment by tiepvupsu** [comment]
![image](https://user-images.githubusercontent.com/2201237/77030071-c4ec1200-695a-11ea-8920-a56cfbdd1e3e.png)
https://d2l.aivivn.com/chapter_linear-networks/softmax-regression_vn.html
không mở ngoặc ở tiêu đề

**Comment by tiepvupsu** [comment]
> Link anh ơi

https://d2l.aivivn.com/chapter_linear-networks/softmax-regression_vn.html

**Comment by tiepvupsu** [comment]
![image](https://user-images.githubusercontent.com/2201237/77030095-dcc39600-695a-11ea-8b15-6e9e4174c797.png)
Không mở ngoặc ở tiêu đề. 
`and thus`

**Comment by duythanhvn** [comment]
All fixed.
