### ISSUE TITLE
Dịch "environment_vn" - Phần 1 (Deprecated)

### ISSUE THREAD

**Issue by duythanhvn** [aivivn/d2l-vn#992]
Phần cần dịch: https://github.com/aivivn/d2l-vn/blame/master/chapter_multilayer-perceptrons/environment_vn.md#L1-L41

### Hướng dẫn
- [Dịch trực tiếp trên website](https://github.com/aivivn/d2l-vn/blob/master/CONTRIBUTING.md).
- Sau khi nhấn vào phần cần dịch ở trên, hãy chọn **Normal view** và làm theo hướng dẫn ở trên để có thể bắt đầu dịch.

![](https://raw.githubusercontent.com/aivivn/d2l-vn/master/translation_team/normal-view.png)

**Comment by NinjaKing** [comment]
Em mới join group hôm nay. Em xin nhận dịch phần này để làm quen. @tiepvupsu

**Comment by duythanhvn** [comment]
@NinjaKing Cảm ơn em đã tham gia. Cho mình hỏi, em đã tham gia Slack của nhóm dịch chưa nhỉ?

**Comment by NinjaKing** [comment]
Em đã tham gia rồi. Để em tự giới thiệu trong nhóm ạ. Thanks anh!

**Comment by duythanhvn** [comment]
@NinjaKing Phần này khi nào em lên được nhỉ?

**Comment by NinjaKing** [comment]
@duythanhvn Em dự kiến khoảng 31/3 ạ. Vì công việc của em hiện tại hơi nhiều nên mỗi ngày em chỉ dành ra được khoảng 1h để dịch.

**Comment by duythanhvn** [comment]
@NinjaKing Chà, nếu vậy thì phần này anh tạm un-assigned em nhé. Anh vừa kiểm tra qua phần dịch của em thấy cũng mới được 1 phần nhỏ.

Hiện tại phần này đang có cập nhật nội dung nên anh khá chờ nội dung này lên ít nhất là trong cuối tuần này để xử lý cho kịp tiến độ dự án. Với lại anh thấy việc này đang tạo áp lực cho em, em đang nhiều việc thì nên ưu tiên việc xử lý này; dự án này không nên góp thêm một phần công việc và áp lực cho em.

Tiến độ dự án này anh vẫn phải đảm bảo (31/3 thì không ổn), nên anh đề xuất khi nào em thoải mái thời gian hơn thì quay lại hỗ trợ dự án em nha. Ở đây nhiều bạn lâu lâu quay lại, dịch 1-2 phần, nhóm vẫn rất hoan nghênh nghen. Cảm ơn em nhé!

**Comment by NinjaKing** [comment]
Ok anh. Vậy để em commit hết phần em đã làm.

**Comment by duythanhvn** [comment]
Ừa, em có thể remove branch đấy ở fork repo của em. Không cần commit lên đâu nha em.
